### PR TITLE
Session proposal

### PR DESCRIPTION
**Pull request by mrcabellom**
Using AI techniques to create hyper realistic digital twins

### CODE REVIEW

**Comment by JJ** [comment]
Thanks for the contribution. Please bear in mind that this is not so much a session as a 10-minute fast talk. Would your "session" proposal fit that format?

**Comment by mrcabellom** [comment]
Hello, Thanks for the answer. No problem, this session will fit the format of 10 minutes + 5 QA.

**Comment by JJ** [comment]
> Hello, Thanks for the answer. No problem, this session will fit the format of 10 minutes + 5 QA.

You might want to adapt the description of the talk then?

**Comment by mrcabellom** [comment]
I have just made the changes. Thanks for your suggestions!

**Review by JJ — APPROVED** [review]
:+1:

**Pull request merged**
